# Generated by Django 4.0.1 on 2022-03-09 12:30

from django.db import migrations
import users.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profiles_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='user_avatar',
            field=users.fields.CustomImageField(default='default_avatar.png', upload_to=users.models.CustomFilePath),
        ),
    ]
