# Generated by Django 4.0.1 on 2022-03-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profiles_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='user_signature',
            field=models.CharField(default='This man is too lazy to write anything.', max_length=50),
        ),
    ]
