# Generated by Django 4.0.1 on 2022-03-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profiles_user_signature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={'verbose_name': 'user_profiles'},
        ),
    ]
