# Generated by Django 4.0.1 on 2022-03-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profiles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={'verbose_name': 'user_profile'},
        ),
    ]
