# Generated by Django 4.0.1 on 2022-01-18 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('videoID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('videoTitle', models.CharField(max_length=25, null=True)),
                ('uploadTime', models.DateField(auto_now_add=True)),
                ('video', models.FileField(upload_to='videos')),
                ('videoIntroduction', models.TextField(blank=True)),
            ],
        ),
    ]
