# Generated by Django 4.0.1 on 2022-01-21 07:44

from django.db import migrations, models
import full_test.models


class Migration(migrations.Migration):

    dependencies = [
        ('full_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='videoPoster',
            field=models.ImageField(blank=True, default='avartars/default avatar.png', height_field='720px', null=True, upload_to=full_test.models.CustomUploadPath, verbose_name='avartars', width_field='1280px'),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='video',
            field=models.FileField(upload_to=full_test.models.CustomUploadPath),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='videoIntroduction',
            field=models.TextField(blank=True, default='No introduction! Sorry...'),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='videoTitle',
            field=models.CharField(default="Distributor doesn't upload title!!", max_length=25, null=True),
        ),
    ]
