# Generated by Django 4.0.1 on 2022-02-11 10:16

from django.db import migrations
import full_test.fields
import full_test.models


class Migration(migrations.Migration):

    dependencies = [
        ('full_test', '0003_alter_videoupload_videoposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='video',
            field=full_test.fields.CustomFileField(upload_to=full_test.models.CustomUploadPath),
        ),
    ]
