# Generated by Django 4.0.1 on 2022-03-10 12:30

from django.db import migrations, models
import full_test.models


class Migration(migrations.Migration):

    dependencies = [
        ('full_test', '0006_videoupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='videoPoster',
            field=models.ImageField(blank=True, default='videoposters/default videoposter.jpg', null=True, upload_to=full_test.models.CustomUploadPath, verbose_name='video_poster'),
        ),
    ]
